---
- name: Initial update and installs
  hosts: "*"
  become: true
  tasks:
    - name: Apt update
      apt:
        update_cache: true
        upgrade: 'yes'
  
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
    
    - name: Install tmux
      apt:
        name: tmux
        state: present
        update_cache: true

    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: true

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: true

    - name: Install nfs-common
      apt:
        name: nfs-common
        state: present
        update_cache: true

    - name: Install nano
      apt:
        name: nano
        state: present
        update_cache: true

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: true

# play 2
- name: Set timezone and aliases
  hosts: "*"
  become: true
  tasks:
    - name: Set timezone
      ansible.builtin.shell: timedatectl set-timezone America/Los_Angeles
    - name: Copy bash aliases
      ansible.builtin.template: src=../templates/bash_aliases dest=/home/radpivm/.bash_aliases

# play 3
- name: Install docker on ubuntu
  hosts: "*"
  become: true
  tasks:
    - name: Run docker install script
      ansible.builtin.script: scripts/install-docker-ubuntu.sh

...
