---

- name: install latest nfs-common
  hosts: "*"
  tasks:
    - name: install nfs-common
      become: true
      apt:
        name: nfs-common
        state: present
        update_cache: true
      

...