---
- name: Set timezone and aliases
  hosts: "*"
  tasks:
    - name: Set timezone
      become: true
      ansible.builtin.timezone: timedatectl set-timezone America/Los_Angeles

    - name: Copy bash aliases
      ansible.builtin.template: 
        src: ../templates/bash_aliases 
        dest: /home/radpivm/.bash_aliases
...